# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Fabian Kutschera
# Description of the Site
description: Geopyhsics PhD Student @ Scripps (UCSD)
# URL of Image of the Site
site-image: /assets/images/Bewerbungsfoto_Hemd_quadrat.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/background_mesh_HFFZ_eta.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: fkutschera@ucsd.edu
# facebook_username: /
twitter_username: KutscheraFabian
# instagram_username: /
linkedin_username: fabian-kutschera
github_username:  fabian-kutschera
# youtube_channel_id: /
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: G-X0M9CMSSTH

# Disqus
disqus-shortname: https-fabian-kutschera-github-io

# Name of the Author
author-name: Fabian Kutschera
# URL for the Image of the Author
author-image: /assets/images/Bewerbungsfoto_Hemd_quadrat.jpg
# 60 Words About the Author
author-about: I am currently a Geopyhsics PhD student at the Institute of Geophysics and Planetary Physics (IGPP), a division of the Scripps Institution of Oceanography (SIO), part of UC San Diego (UCSD). In 2023, I completed the International Masters Programme in Geophysics offered by LMU and TUM in Munich, Germany. My current focus lies on computational seismology, earthquake dynamic rupture modeling, and tsunami genesis caused by coseismic seafloor displacement. I combined both of these fields in my MSc Thesis about the 2020 Mw 7.0 Samos earthquake and tsunami and in my BSc Thesis. The latter covered earthquake-tsunami modeling for a strike-slip fault system in North Iceland, following a physics-based approach and using high performance computing. Extended results were presented at the virtual EGU General Assembly 2021, on-site at EGU GA 2022, as well as at NorthQuake 2022. Please check the <a href="/publications">publications</a>/<a href="/conferences">conferences</a> tab for more information. I've been a TA for the EarthScope (formerly IRIS) Seismology Skill Building Workshop in the summer of 2023. In addition to academia, I gained first experience in the reinsurance industry and supported the Cat Risk Management Team (R&D, GIS and Portfolio Analytics) at Allianz SE Reinsurance.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/fabian-kutschera

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
