# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Fabian Kutschera
# Description of the Site
description: MSc Geophysics Student @ LMU and TU Munich
# URL of Image of the Site
site-image: /assets/images/Bewerbungsfoto_Hemd_quadrat.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/background_mesh_HFFZ_eta.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: fabian.kutschera@geophysik.uni-muenchen.de
# facebook_username: /
twitter_username: KutscheraFabian
# instagram_username: /
linkedin_username: fabian-kutschera
github_username:  fabian-kutschera
# youtube_channel_id: /
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: fabian-kutschera

# Name of the Author
author-name: Fabian Kutschera
# URL for the Image of the Author
author-image: /assets/images/Bewerbungsfoto_Hemd_quadrat.jpg
# 60 Words About the Author
author-about: I am currently attending the Masters Programme in Geophysics offered by LMU and TUM in Munich. My focus lies on seismology and tsunami genesis caused by coseismic seafloor displacement. I already combined both of these fields in my Bachelors Thesis, which covered earthquake-tsunami modelling in North Iceland, following a physics-based approach and using high performance computing. Extended results were presented at the virtual EGU General Assembly 2021 as well as on-site at EGU GA 2022 and at NorthQuake 2022. In addition to the research field, I gained first experience within the reinsurance industry and supported the Cat Risk Management Team (R&D, GIS and Portfolio Analytics) at Allianz SE Reinsurance.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/fabian-kutschera

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
