name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        #docker run \
        #-v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        #jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future --trace"
        # https://github.com/envygeeks/jekyll-docker/issues/363
        export JEKYLL_VERSION=4.3.3
        docker run --rm \
        --volume="$PWD:/srv/jekyll:Z" \
        -t jvconseil/jekyll-docker:$JEKYLL_VERSION \
        jekyll build --trace

